name: widepixelimage
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  dio: ^4.0.4
  #  alice: ^0.2.1
  shared_preferences: ^2.0.13
  #  photo_view: ^0.11.1
  #  bubble_tab_indicator: ^0.1.6
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  lottie: ^1.2.2
  flutter_svg: ^1.0.3
  #  flutter_tags: ^0.4.9+1
  flutter_staggered_grid_view: ^0.6.1
  #  random_color: ^1.0.6-nullsafety
  sliding_up_panel: ^2.0.0+1
  #  photo_view: ^0.11.0
  intl: ^0.17.0
  peanut: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/



