name: widepixelimage
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  dio: ^5.7.0
  #  alice: ^0.2.1
  shared_preferences: ^2.0.11
  #  photo_view: ^0.11.1
  #  bubble_tab_indicator: ^0.1.6
  carousel_slider: ^5.0.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  lottie: ^3.3.0
  flutter_svg: ^2.0.16
  #  flutter_tags: ^0.4.9+1
  flutter_staggered_grid_view: ^0.7.0
  #  random_color: ^1.0.6-nullsafety
  sliding_up_panel: ^2.0.0+1
  #  photo_view: ^0.11.0
  intl: ^0.20.1
  peanut: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/



